### ISSUE TITLE
Startup crash related to vsync

### ISSUE THREAD

**Issue by wolfiestyle** [rg3dengine/rg3d#79]
I'm following the first part of the 3d shooter tutorial, and running the code gives me this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ContextCreationError(CreationErrors([NoAvailablePixelFormat, OsError("Couldn\'t setup vsync: expected interval `1` but got `0`")]))', src/main.rs:43:73
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /home/wolfie/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: r3dtest::main
             at ./src/main.rs:43:22
   5: core::ops::function::FnOnce::call_once
             at /home/wolfie/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

The offending line is:
```Rust
let mut engine = GameEngine::new(window_builder, &event_loop, true).unwrap();
```

Changing the last parameter to `false` works, so something related to vsync seems to be broken.

I'm using Gentoo Linux x86_64, xfce desktop, and ryzen 3800x / RX 570 (amdgpu).

**Comment by mrDIMAS** [comment]
Hm, I need to check if winit provides a way of checking if vsync is available or not. I'll try to fix it asap because it affects my other projects too.

**Comment by mrDIMAS** [comment]
Fixed this in the tutorial and added the note about vsync flag.

**Comment by tukanoidd** [comment]
This error appears for me (but without the text after the error name) on Wayland, while on Xorg it's fine (RTX2070TI, latest drivers, not using integrated graphics, Garuda Linux (Arch))
